2024-01-31 19:33:40,349 ERROR ZomatoRestaurants:143 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10003'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=54199&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 502 Bad Gateway')))
2024-01-31 19:42:44,630 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10067'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19444584&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 502 Bad Gateway')))
2024-01-31 19:43:00,370 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10002'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Read timed out. (read timeout=10)
2024-01-31 19:47:29,579 ERROR GoogleReviews:48 - None | 
2024-01-31 19:47:37,774 ERROR GoogleReviews:42 - {"statusCode": 400, "error": "'NoneType' object is not iterable", "request_params": {"hex_id": "0x3bae3d78c39ed1d7:0x6832860dbb5cd434", "num_reviews": 15807, "fetch_latest": "true", "fetch_additional_data": false}}
2024-01-31 19:47:37,776 ERROR GoogleReviews:48 - None | 
2024-01-31 19:48:07,316 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10009'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Read timed out. (read timeout=10)
2024-01-31 19:48:07,330 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10009'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Read timed out. (read timeout=10)
2024-01-31 19:48:07,432 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10000'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Read timed out. (read timeout=10)
2024-01-31 19:48:09,346 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10064'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Read timed out. (read timeout=10)
2024-01-31 19:48:10,289 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10064'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Read timed out. (read timeout=10)
2024-01-31 19:48:10,468 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10001'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19608368&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09022ac370>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:10,470 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10006'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19084788&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0901171810>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:10,470 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10032'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=50201&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09022ae0e0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:10,471 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10003'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=52333&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0902128580>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:10,745 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10031'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Read timed out. (read timeout=10)
2024-01-31 19:48:10,756 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10000'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Read timed out. (read timeout=10)
2024-01-31 19:48:13,148 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10033'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Read timed out. (read timeout=10)
2024-01-31 19:48:13,541 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10001'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18436379&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0901173910>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:13,542 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10004'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19084788&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09022ad660>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:13,543 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10000'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=52333&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0901173160>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:13,544 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10001'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=50201&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0901170a30>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:13,544 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10003'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19714949&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09022ae320>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:13,547 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10005'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=53178&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0901173820>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:13,548 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10067'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19608368&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f090122b940>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:14,389 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10033'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Read timed out. (read timeout=10)
2024-01-31 19:48:14,401 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10030'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Read timed out.
2024-01-31 19:48:16,613 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10067'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19925361&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8e28430>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:16,614 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10005'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18774218&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8e29ff0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:16,615 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10003'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=52673&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8e28c40>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:16,615 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10007'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=60560&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8e2ad10>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:16,616 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10031'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18436379&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8e296c0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:16,617 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10065'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=53382&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09011722c0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:16,618 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10030'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19714949&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8e28460>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:16,622 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10033'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=53178&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f0c400>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:16,624 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10000'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18232657&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8e29d50>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:16,625 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10067'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=60292&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09011717b0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:19,688 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10033'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=52413&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f0db40>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:19,688 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10068'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=53382&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8fac880>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:19,688 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10066'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=20035714&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f0db10>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:19,688 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10005'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=60560&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8fac640>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:19,689 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10008'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=60292&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8fad6c0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:19,689 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10031'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=52673&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f0f850>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:19,689 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10002'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18774218&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8fac7c0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:19,690 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10033'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=54225&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09011713f0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:19,690 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10065'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19925361&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f0eb90>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:19,690 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10004'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18232657&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8facf40>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:22,756 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10001'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18613313&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8faf2e0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:22,756 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10034'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18232657&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f96c50>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:22,756 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10067'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=52413&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f94190>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:22,757 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10005'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=54225&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f95e10>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:22,757 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10003'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=52673&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f94fd0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:22,757 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10004'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19925361&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f96530>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:22,758 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10003'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=53893&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8faeaa0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:22,759 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10005'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18774218&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f956f0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:22,759 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10008'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=20035714&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f948b0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:22,759 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10068'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18232670&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8fade40>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:25,833 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10003'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=58723&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f01a80>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:25,834 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10009'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18232670&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09011a8340>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:25,835 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10031'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=52413&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f02650>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:25,836 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10004'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=53893&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f034c0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:25,836 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10034'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19006047&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f011e0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:25,837 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10005'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18613313&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f01f60>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:25,838 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10030'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=20035714&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09011a8220>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:25,838 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10009'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18537454&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f00850>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:25,841 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10006'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=54225&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f02da0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:25,842 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10030'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=56598&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f96fb0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:28,901 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10008'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=58723&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8fae260>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:28,902 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10003'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18232670&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8faf340>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:28,902 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10009'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=53893&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8fae6b0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:28,903 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10008'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=51649&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f95ed0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:28,903 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10008'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=53528&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8faf0a0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:28,904 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10032'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=56580&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f945b0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:28,905 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10030'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18613313&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f0ea70>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:28,905 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10002'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=56598&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f0ef50>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:28,906 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10003'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18537454&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f0dea0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:28,908 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10031'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19006047&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f0f040>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:31,973 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10031'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=56580&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8e29840>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:31,974 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10030'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18537454&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09011725c0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:31,974 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10008'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=50579&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0902134850>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:31,976 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10002'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19006047&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0901171cf0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:31,977 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10030'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19539791&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f0e260>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:31,977 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10008'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18419856&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8f0da20>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:31,979 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10007'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=56598&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8e2a980>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:31,982 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10065'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=58723&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8e29120>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:31,985 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10068'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=53528&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8e29870>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:31,985 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10067'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=51649&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08e8e2abf0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:35,049 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10004'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=60374&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0901173ca0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:35,050 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10032'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=50388&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09011703d0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:35,051 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10033'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18419856&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09011aaf80>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:35,052 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10009'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=50017&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09011a9570>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:35,053 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10000'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=56580&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09011a9a20>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:35,053 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10000'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=51649&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09011abdc0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:35,054 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10030'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18660622&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09011a8e20>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:35,055 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10068'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19539791&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09011aa860>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:35,056 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10031'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=50579&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09011aa140>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:35,058 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10003'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=53528&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09011ab6a0>: Failed to establish a new connection: [Errno 113] No route to host')))
2024-01-31 19:48:45,112 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10002'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=51240&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0901191ae0>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:48:45,119 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10034'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18353108&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09011936a0>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:48:45,126 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10067'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19124358&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0901193220>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:48:46,080 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10004'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=60374&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09011900d0>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:48:46,092 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10003'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=50388&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0901191b40>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:48:46,100 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10033'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18419856&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09011911b0>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:48:46,106 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10064'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=50017&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0901191840>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:48:46,121 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10000'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18660622&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09011084c0>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:48:46,124 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10006'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19539791&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0901108be0>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:48:46,131 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10030'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=50579&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0901109300>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:48:56,154 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10034'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18547241&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09011098a0>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:06,759 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10005'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=56671&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0901193550>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:07,664 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10065'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Read timed out. (read timeout=10)
2024-01-31 19:49:08,103 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10065'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=20058862&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 502 Bad Gateway')))
2024-01-31 19:49:10,308 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10065'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19966536&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09011097b0>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:15,695 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10066'} | ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-01-31 19:49:18,685 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10068'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19577417&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0901171e10>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:19,408 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10064'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Read timed out. (read timeout=10)
2024-01-31 19:49:21,592 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10006'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18706501&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09011934c0>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:27,222 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10001'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=50789&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f090110b130>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:30,438 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10030'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=20058862&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0901193760>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:30,445 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10030'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18681550&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0901192c80>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:31,104 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10007'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=20030607&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09011906a0>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:31,109 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10031'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19996287&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f090110b2e0>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:33,433 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10031'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19539137&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0901192020>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:34,756 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10066'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=53391&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f090110a170>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:35,166 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10030'} | ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-01-31 19:49:37,156 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10005'} | ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-01-31 19:49:38,857 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10064'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=60340&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f090110bd60>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:41,724 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10064'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19332331&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0901109fc0>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:42,136 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10068'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19996287&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09010d9570>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:43,823 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10001'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=54372&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f090110b6a0>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:43,826 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10066'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18676537&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09010dafb0>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:46,188 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10002'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=53084&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0901170dc0>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:48,184 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10066'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=50789&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f090110ad70>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:50,240 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10001'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Read timed out. (read timeout=10)
2024-01-31 19:49:52,744 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10001'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19332331&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0901173580>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:54,358 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10067'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=19163398&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09010d9030>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:54,849 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10005'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=54372&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0901193d60>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:54,854 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10067'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18676537&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0901192a10>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:49:58,200 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10033'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=53381&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0901193a00>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
2024-01-31 19:50:57,556 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10066'} | ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-01-31 19:51:04,508 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10068'} | ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-01-31 19:51:21,965 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10000'} | ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-01-31 19:51:25,127 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10000'} | ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-01-31 19:51:27,147 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10001'} | ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-01-31 19:51:37,671 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10009'} | ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-01-31 19:51:42,226 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10064'} | ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2024-01-31 19:51:50,984 ERROR ZomatoRestaurants:129 - {'https': 'http://vsatyen:unWLWiVPCd@107.181.187.120:10067'} | HTTPSConnectionPool(host='www.zomato.com', port=443): Max retries exceeded with url: /webroutes/reviews/loadMore?res_id=18756010&filter=reviews-dd&sort=da (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f09011906d0>, 'Connection to 107.181.187.120 timed out. (connect timeout=10)')))
